# Autogenerated from a Treetop grammar. Edits may be lost.


module OOPM
module Parsing

module Reference
  include Treetop::Runtime

  def root
    @root ||= :reference
  end

  include Keyword

  module Reference0
    def keyword
      elements[0]
    end

  end

  module Reference1
  end

  def _nt_reference
    start_index = index
    if node_cache[:reference].has_key?(index)
      cached = node_cache[:reference][index]
      if cached
        cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0, s0 = index, []
    i1 = index
    i2, s2 = index, []
    r3 = _nt_keyword
    s2 << r3
    if r3
      i4 = index
      if has_terminal?('\G[_a-zA-Z0-9]', true, index)
        r5 = true
        @index += 1
      else
        r5 = nil
      end
      if r5
        r4 = nil
      else
        @index = i4
        r4 = instantiate_node(SyntaxNode,input, index...index)
      end
      s2 << r4
    end
    if s2.last
      r2 = instantiate_node(SyntaxNode,input, i2...index, s2)
      r2.extend(Reference0)
    else
      @index = i2
      r2 = nil
    end
    if r2
      r1 = nil
    else
      @index = i1
      r1 = instantiate_node(SyntaxNode,input, index...index)
    end
    s0 << r1
    if r1
      if has_terminal?('\G[_a-zA-Z]', true, index)
        r6 = true
        @index += 1
      else
        r6 = nil
      end
      s0 << r6
      if r6
        s7, i7 = [], index
        loop do
          if has_terminal?('\G[_a-zA-Z0-9]', true, index)
            r8 = true
            @index += 1
          else
            r8 = nil
          end
          if r8
            s7 << r8
          else
            break
          end
        end
        r7 = instantiate_node(SyntaxNode,input, i7...index, s7)
        s0 << r7
      end
    end
    if s0.last
      r0 = instantiate_node(ReferenceNode,input, i0...index, s0)
      r0.extend(Reference1)
    else
      @index = i0
      r0 = nil
    end

    node_cache[:reference][start_index] = r0

    r0
  end

end

class ReferenceParser < Treetop::Runtime::CompiledParser
  include Reference
end


end
end
