require 'oopm/version'

require 'treetop'
require 'oopm/parsing/whitespace'
require 'oopm/parsing/number'
require 'oopm/parsing/name'
require 'oopm/parsing/string_literal'
require 'oopm/parsing/any_object'
require 'oopm/parsing/binary_operation'
require 'oopm/parsing/expression'